Moved build-dos command inside digabi-dev package.

diff --git a/custom-packages/digabi-dev/scripts/os b/custom-packages/digabi-dev/scripts/os
--- a/custom-packages/digabi-dev/scripts/os
+++ b/custom-packages/digabi-dev/scripts/os
@@ -40,7 +40,13 @@ case "${COMMAND}" in
 		info "Successfully checked out commit ${COMMIT}, created branch ${BRANCH}."
 		;;
 	*)
-		error "Invalid command: ${COMMAND}."
-		exit 1
+	    SCRIPT_PATH="$(dirname $0)/_os"
+	    if [ -x "${SCRIPT_PATH}/${COMMAND}" ]
+	    then
+	        ${SCRIPT_PATH}/${COMMAND} $@
+	    else
+	   		error "Invalid command: ${COMMAND}."
+	    	exit 1
+	    fi
 		;;
 esac
