Updated architecture

diff --git a/auto/config b/auto/config
--- a/auto/config
+++ b/auto/config
@@ -11,12 +11,12 @@ case "${ARCHITECTURE}" in
         _SOURCE="false"
         ;;
     i386)
-        _LINUX_FLAVOURS="486 686-pae"
+        _LINUX_FLAVOURS="686"
         _SOURCE="false"
         ;;
     *)
-	_LINUX_FLAVOURS="686-pae"
-	_SOURCE="false"
+	echo "Invalid architecture!"
+	exit 1
 esac
 
 
@@ -32,7 +32,7 @@ lb config noauto \
     --apt-http-proxy "http://localhost:3142/" \
     --distribution "${DISTRIBUTION}" \
     --linux-flavour "${_LINUX_FLAVOURS}" \
-    --linux-packages "linux-image linux-headers" \
+    --linux-packages "digabi-kernel" \
     --apt-indices false \
     --apt-recommends false \
     --bootappend-live "${BOOTAPPEND_LIVE}" \
