Added support for switching between global and user-specific config files.

diff --git a/custom-packages/digabi-common/usr/lib/digabi/scripts/config b/custom-packages/digabi-common/usr/lib/digabi/scripts/config
--- a/custom-packages/digabi-common/usr/lib/digabi/scripts/config
+++ b/custom-packages/digabi-common/usr/lib/digabi/scripts/config
@@ -3,9 +3,24 @@
 set -e
 
 COMMAND="$1"
-KEY="$2"
+if [ "$2" = "--global" ]
+then
+    GLOBAL="true"
+    KEY="$3"
+    shift
+else
+    KEY="$2"
+fi
 
 # TODO: If --global, use /etc/digabi as configuration path, else use ~/.digabi
+
+info() {
+    echo "I: $@"
+}
+
+error() {
+    echo "E: $@"
+}
 
 usage() {
     echo "Usage: $0 {get|set|source|conf-file|show} <key> [value]"
@@ -47,10 +62,22 @@ case "${COMMAND}" in
         echo "${CONFIG_FILE}"
         ;;
     source)
-        # TODO: Source (. /path/to/file) config file
+        if [ -f "${CONFIG_FILE}" ]
+        then
+            . "${CONFIG_FILE}"
+        else
+            error "Config file not found: ${CONFIG_FILE}."
+            exit 1
+        fi
         ;;
     show)
-        # TODO: Show config file
+        if [ -f "${CONFIG_FILE}" ]
+        then
+            cat "${CONFIG_FILE}"
+        else
+            error "Config file not found: ${CONFIG_FILE}."
+            exit 1
+        fi
         ;;
     **)
         echo "Invalid command: ${COMMAND}, exiting..."
